export const FETCH_SERIES_BEGIN = 'FETCH_SERIES_BEGIN';
export const FETCH_SERIES_SUCCESS = 'FETCH_SERIES_SUCCESS';
export const FETCH_SERIES_FAILURE = 'FETCH_SERIES_FAILURE';
export const FETCH_DATA_BEGIN = 'FETCH_DATA_BEGIN';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const PAGINATION = 'PAGINATION';

export const HOMEPAGE = 'HOMEPAGE';
export const PROFILE = 'PROFILE';
export const ARCHIVE = 'ARCHIVE';
export const REGLEMENT = 'REGLEMENT';
export const FAHRERWERTUNG = 'FAHRERWERTUNG';
export const TEAMWERTUNG = 'TEAMWERTUNG';
export const RENNKALENDER = 'RENNKALENDER';
export const ERGEBNIS = 'ERGEBNIS';
